#!/usr/bin/env python2

import io
import os
import yaml

with open('/etc/prometheus.yml', 'r') as stream:
    prom_config = yaml.load(stream)
ssm_config = {'users': [[x for x in prom_config['scrape_configs'] if x['job_name'] == 'linux'][0]['basic_auth']]}

if ssm_config['users'][0]['username'] != 'ssm' or ssm_config['users'][0]['password'] != 'ssm':
    with io.open('/srv/update/ssm-manage.yml', 'w', encoding='utf8') as outfile:
        yaml.dump(ssm_config, outfile, default_flow_style=False, allow_unicode=True)
    os.chmod('/srv/update/ssm-manage.yml', 0640)
